spring:
  application:
    name: coordinator
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
coordinator:
  loaders:
#    - 127.0.0.1:9099
  extractors:
#    - 127.0.0.1:9088
logging:
  config: classpath:log4j2.yml